### ISSUE TITLE
How do I play?

### ISSUE THREAD

**Issue by DLWAwesome** [Kenny2github/multisnake#1]
I can't play, and also couldn't read the downloads. :snake:

**Comment by Kenny2github** [comment]
You need to have [python](https://www.python.org) [installed](https://www.python.org/download), and additionally you need to have Pygame installed. After installing python (make sure you have `pip`!) run this:
```bash
pip install pygame --user
```
Then run `snake.py` and it should work

**Comment by DLWAwesome** [comment]
I have python, how do I install pygame?
